# Generated by Django 3.2.2 on 2021-11-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='full_mile',
        ),
        migrations.AddField(
            model_name='split',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(),
        ),
    ]
